hypertrace/java-grpc-utils

- grpc-client-utils/src/main/java/org/hypertrace/core/grpcutils/client/RequestContextAsCreds.java
- grpc-client-utils/src/test/java/org/hypertrace/core/grpcutils/client/ContextKeyBasedCredsTest.java
- grpc-client-utils/src/test/java/org/hypertrace/core/grpcutils/client/GrpcClientRequestContextUtilTest.java
- grpc-server-utils/src/main/java/org/hypertrace/core/grpcutils/server/RequestContextServerInterceptor.java
- grpc-server-utils/src/test/java/org/hypertrace/core/grpcutils/server/RequestContextServerInterceptorTests.java
Based on the name of the header, if the header ends with `-bin` then it is considered a binary header and a BINARY_BYTE_MARSHALLER is used in that case.
> Added parsing of binaryheaders in RequestContext

- build.gradle.kts
- grpc-client-utils/build.gradle.kts
- grpc-context-utils/build.gradle.kts
- grpc-server-rx-utils/build.gradle.kts
- grpc-server-rx-utils/src/main/java/org/hypertrace/core/grpcutils/server/rx/ServerCallStreamRxObserver.java
- grpc-server-rx-utils/src/test/java/org/hypertrace/core/grpcutils/server/rx/ServerCallStreamRxObserverTest.java
- grpc-server-utils/build.gradle.kts
- settings.gradle.kts
This change adds an RxJava adapter to support converting a reactive construct (Observable, Single, Maybe, Completable - didn't add flowable support unless needed) into a GRPC response. This pattern:
- Promotes cleaner code, as an observer no longer needs to be plumbed down throw the call stack
- Supports either synchronous or async implementations (like any reactive code)
- Supports cancellation for ongoing requests
> feat: add server call stream observer for rx

- grpc-client-rx-utils/src/main/java/org/hypertrace/core/grpcutils/client/rx/DefaultGrpcRxExecutionContext.java
- grpc-client-rx-utils/src/main/java/org/hypertrace/core/grpcutils/client/rx/GrpcRxExecutionContext.java
- grpc-client-rx-utils/src/test/java/org/hypertrace/core/grpcutils/client/rx/DefaultGrpcRxExecutionContextTest.java
- grpc-client-rx-utils/src/test/java/org/hypertrace/core/grpcutils/client/rx/GrpcRxExecutionContextTest.java
- grpc-context-utils/src/main/java/org/hypertrace/core/grpcutils/context/RequestContext.java
- grpc-context-utils/src/test/java/org/hypertrace/core/grpcutils/context/RequestContextTest.java
In ingestion scenarios, we often have to read the tenant id off incoming data explicitly and then add it to outbound requests. We currently support this through the imperative client utils, but this change adds it to the rx utils as well, in addition to simplifying the underlying syntax.
> refactor: add shortcut to create a tenant id request context

- grpc-client-rx-utils/build.gradle.kts
- grpc-client-utils/build.gradle.kts
- grpc-client-utils/src/main/java/org/hypertrace/core/grpcutils/client/GrpcClientRequestContextUtil.java
- grpc-client-utils/src/test/java/org/hypertrace/core/grpcutils/client/GrpcClientRequestContextUtilTest.java
- grpc-context-utils/build.gradle.kts
- grpc-server-rx-utils/build.gradle.kts
- grpc-server-utils/build.gradle.kts
This changes the behavior of the execution utils to stop wrapping any thrown exceptions. This behavior was only meant to satisfy the compiler, and makes it more difficult to react based on the type of error.
> fix: unwrap thrown exceptions

- grpc-client-utils/build.gradle.kts
- grpc-client-utils/src/main/java/org/hypertrace/core/grpcutils/client/GrpcChannelRegistry.java
- grpc-client-utils/src/test/java/org/hypertrace/core/grpcutils/client/GrpcChannelRegistryTest.java
This channel registry, ported from https://github.com/hypertrace/hypertrace-core-graphql/blob/7df21a96bf0712e239ced1117c49889870cf7b3e/hypertrace-core-graphql-grpc-utils/src/main/java/org/hypertrace/core/graphql/utils/grpc/DefaultGrpcChannelRegistry.java is used by clients to prevent multiple places in code from instantiating the same channel (which grpc strongly discourages), instead sharing channels and allowing centralized shutdown.
Added UT
> feat: add grpc channel registry

- grpc-context-utils/src/main/java/org/hypertrace/core/grpcutils/context/Jwt.java
- grpc-context-utils/src/main/java/org/hypertrace/core/grpcutils/context/JwtParser.java
- grpc-context-utils/src/main/java/org/hypertrace/core/grpcutils/context/RequestContext.java
- grpc-context-utils/src/test/java/org/hypertrace/core/grpcutils/context/JwtParserTest.java
- grpc-context-utils/src/test/java/org/hypertrace/core/grpcutils/context/RequestContextTest.java
Add roles parsing logic to JWT parser and expose roles in request context.
The main motivation is to be able to reuse this logic in other parts of codebase, specifically in graphql context
Added unit tests
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.
> ENG-9494 expose roles in request context

- grpc-client-utils/src/main/java/org/hypertrace/core/grpcutils/client/GrpcChannelRegistry.java
- grpc-client-utils/src/test/java/org/hypertrace/core/grpcutils/client/GrpcChannelRegistryTest.java
Add supports to the channel registry to create different plaintext and secure channels, differentiating the two.
Added UTs
> refactor: add registry support for secure channels

- grpc-server-utils/build.gradle.kts
- grpc-server-utils/src/main/java/org/hypertrace/core/grpcutils/server/ServerManagementUtil.java
- grpc-server-utils/src/test/java/org/hypertrace/core/grpcutils/server/ServerManagementUtilTest.java
We are working on being good grpc users, and part of that is fully shutting down our servers. In most places today we either don't shut down, or don't wait for shutdown to complete due to some confusion in the various shutdown APIs. This new util makes it easy for servers to shutdown correctly.
Added UT, also tested locally with a service.
> feat: add server shutdown util

- grpc-client-rx-utils/build.gradle.kts
- grpc-client-utils/build.gradle.kts
- grpc-context-utils/build.gradle.kts
- grpc-server-rx-utils/build.gradle.kts
- grpc-server-utils/build.gradle.kts
A number of things going on here. 
- Upgrading jackson and grpc along with some other minor dependencies
- Switching to using the grpc bom which will prevent other projects upgrading from getting out of sync
- Exposing constraints on known vulnerabilities that are associated with this at runtime: netty, jackson and gson 
Published and verified locally
> feat: upgrade jackson, grpc, constrain vulns and use bom

- grpc-context-utils/src/main/java/org/hypertrace/core/grpcutils/context/DefaultContextualKey.java
- grpc-context-utils/src/main/java/org/hypertrace/core/grpcutils/context/RequestContext.java
- grpc-context-utils/src/test/java/org/hypertrace/core/grpcutils/context/DefaultContextualKeyTest.java
Previously, RequestContext could produce keys from the current request context that assumed it was triggered by a user. While this will always be correct, it can lead to duplication on internal calls where the specific auth context is less important. This extension allows support for both, deprecating the original to force the caller to make an explicit choice.
Added UTs
> feat: add support for more advanced contextual keys

- .github/workflows/pr-test.yml
Codecov bash uploader is being deprecated and is currently in the brownout phase. We need to upgrade to the v2 gh action in all repos.
More info: https://about.codecov.io/blog/codecov-uploader-deprecation-plan/[](https://github.com/tim-mwangi)
> chore: update codecov gha to v2

- grpc-client-utils/build.gradle.kts
- grpc-client-utils/src/main/java/org/hypertrace/core/grpcutils/client/GrpcChannelRegistry.java
- grpc-client-utils/src/main/java/org/hypertrace/core/grpcutils/client/InProcessGrpcChannelRegistry.java
- grpc-client-utils/src/test/java/org/hypertrace/core/grpcutils/client/GrpcChannelRegistryTest.java
- grpc-client-utils/src/test/java/org/hypertrace/core/grpcutils/client/InProcessGrpcChannelRegistryTest.java
Add a version of the channel registry that supports in process channels as well as substituting an in process channel for a known hostname.
Added unit tests
> feat: add in process channel support

- grpc-client-utils/build.gradle.kts
- grpc-server-utils/build.gradle.kts
Previously we were constraining individually vulnerable jars, using the netty bom is a little more straightforward and makes sure all netty jars are on the same version.
> refactor: use bom to constrain netty

- grpc-context-utils/build.gradle.kts
- grpc-context-utils/src/main/java/org/hypertrace/core/grpcutils/context/RequestContext.java
- grpc-context-utils/src/test/java/org/hypertrace/core/grpcutils/context/RequestContextTest.java
Two parts
1. Updated dependencies. This involved a hotfix release for jackson databind that resolved a CVE, and adding a new constraint on proto. Although not directly used, its always used in conjunction with grpc so this was the best common place we had to constrain the version.
2. Added a way to build GRPC trailers from a request context. We already have this conversion as headers in the other direction, but this allows us to propagate things back (in my case, request IDs with errors).
Added UTs
> refactor: add support for trailer building and update deps

- grpc-client-rx-utils/build.gradle.kts
- grpc-client-utils/build.gradle.kts
- grpc-client-utils/src/main/java/org/hypertrace/core/grpcutils/client/RequestContextAsCreds.java
- grpc-context-utils/build.gradle.kts
- grpc-context-utils/src/main/java/org/hypertrace/core/grpcutils/context/DefaultContextualKey.java
- grpc-context-utils/src/main/java/org/hypertrace/core/grpcutils/context/RequestContext.java
- grpc-context-utils/src/test/java/org/hypertrace/core/grpcutils/context/RequestContextTest.java
- grpc-server-rx-utils/build.gradle.kts
- grpc-server-utils/build.gradle.kts
The original implementation of request context assumed headers were case sensitive and single valued. I added support here for case insensitive access (preserving provided case on propagation), and accepting multiple values for the same header name.
Did my best to keep everything 100% backwards compatible if using the old APIs. The only exception I know of is using the deprecated `add` method, using two different cased representations for the same header name will result in an overwrite (which was the previous intention, and missing due to a bug), rather than an addition.
Updated unit tests
> feat: add context support for case insensitive and multivalue

- grpc-server-utils/src/main/java/org/hypertrace/core/grpcutils/server/InterceptorUtil.java
Small change to overload interceptor wrapper to allow accepting a service definition instead of a bindable service. This allows wrapping custom interceptors in addition to the util-defined ones.
> refactor: allow wrapping interceptors around service def

- grpc-client-utils/src/main/java/org/hypertrace/core/grpcutils/client/GrpcChannelRegistry.java
- grpc-client-utils/src/main/java/org/hypertrace/core/grpcutils/client/GrpcRegistryConfig.java
- grpc-client-utils/src/main/java/org/hypertrace/core/grpcutils/client/InProcessGrpcChannelRegistry.java
- grpc-client-utils/src/test/java/org/hypertrace/core/grpcutils/client/GrpcChannelRegistryTest.java
- grpc-client-utils/src/test/java/org/hypertrace/core/grpcutils/client/InProcessGrpcChannelRegistryTest.java
Previously had to either add it on each registry channel call, or subclass the registry.
Added UT
> feat: add registry-level client interceptor support

- grpc-context-utils/build.gradle.kts
- grpc-context-utils/src/main/java/org/hypertrace/core/grpcutils/context/JwtParser.java
Breaking changes in auth0 lib lead to context breakage when running in same jvm as auth0 jwt 4+. Upgrading lib here for compat, and updating claim extraction based on new behavior.
> fix: upgrade jwt lib due to breaking change

- gradle/wrapper/gradle-wrapper.properties
- grpc-client-rx-utils/build.gradle.kts
- grpc-client-utils/build.gradle.kts
- grpc-context-utils/build.gradle.kts
- grpc-server-rx-utils/build.gradle.kts
- grpc-server-utils/build.gradle.kts
- owasp-suppressions.xml
This PR updates grpc as there is a new vulnerability reported on the older version being used - `CVE-2023-33953`
> chore: upgrade grpc due to vuln

- grpc-server-utils/src/main/java/org/hypertrace/core/grpcutils/server/ThrowableResponseInterceptor.java
Stringifying a callstack blindly often overflows header limits. Give the cause and let grpc do the work.
> fix: stop stringifying callstack

- grpc-context-utils/src/main/java/org/hypertrace/core/grpcutils/context/ContextualExceptionDetails.java
- grpc-context-utils/src/main/java/org/hypertrace/core/grpcutils/context/ContextualStatusExceptionBuilder.java
- grpc-context-utils/src/main/java/org/hypertrace/core/grpcutils/context/RequestContext.java
- grpc-context-utils/src/test/java/org/hypertrace/core/grpcutils/context/ContextualExceptionDetailsTest.java
- grpc-context-utils/src/test/java/org/hypertrace/core/grpcutils/context/RequestContextTest.java
- grpc-server-utils/src/main/java/org/hypertrace/core/grpcutils/server/ThrowableResponseInterceptor.java
Add proposal for standard exceptions. Included tests that show how exceptions would be built.
Also:
- Server exception interceptor now sends request context back if trailers aren't already explicitly included
- RequestContext updated to include tenant id in trailers
- RequestContext now supports equals/hashcode
- RequestContext JWT Parser is now static and shared. This seems to match the original intent, as the JWT Parser includes a cache that would only make sense if shared across context. Should help avoid allocations and reduce JWT parsing.
Added UTs. Expect this to be fully backwards compatible.
> feat: standard exceptions

- grpc-client-rx-utils/build.gradle.kts
- grpc-client-utils/build.gradle.kts
- grpc-context-utils/build.gradle.kts
- grpc-context-utils/src/main/java/org/hypertrace/core/grpcutils/context/ContextualExceptionDetails.java
- grpc-context-utils/src/main/java/org/hypertrace/core/grpcutils/context/ContextualStatusExceptionBuilder.java
- grpc-context-utils/src/test/java/org/hypertrace/core/grpcutils/context/ContextualExceptionDetailsTest.java
- grpc-server-rx-utils/build.gradle.kts
- grpc-server-utils/build.gradle.kts
- grpc-server-utils/src/main/java/org/hypertrace/core/grpcutils/server/ThrowableResponseInterceptor.java
- grpc-server-utils/src/test/java/org/hypertrace/core/grpcutils/server/ThrowableResponseInterceptorTest.java
Made context propagation automatic, removed requirement to provide context when creating context.
> refactor: add support for better exception propagation and creation

- .github/workflows/pr-test.yml
- grpc-server-utils/src/main/java/org/hypertrace/core/grpcutils/server/RequestContextServerInterceptor.java
This change updates the request interceptor to fill in the request ID if unset. Previously, we always did this in individual services at the edge but the default interceptor can support writing it if unset which automatically brings support to any GRPC services on the edge (only HTTP services will still need to manually support this).
> chore: support initializing request id

- grpc-client-utils/src/main/java/org/hypertrace/core/grpcutils/client/TimeoutVerifyingClientInterceptor.java
Because we want every call to be made with a timeout, this interceptor (which will be attached by the service framework) highlights any calls missing one.
> chore: add timeout verifying client interceptor

- grpc-server-utils/src/main/java/org/hypertrace/core/grpcutils/server/ExternalExceptionInterceptor.java
This interceptor is meant to be used in edge services to prevent leaking any sensitive information. It only propagates status code, an external message and request ID, if set. All other metadata such as cause and metadata are stripped.
> chore: add external error interceptor

- grpc-client-utils/build.gradle.kts
- grpc-server-utils/build.gradle.kts
> fix: restore netty constraint

- .github/workflows/codeql-analysis.yml
- .github/workflows/pr-build.yml
- .github/workflows/pr-test.yml
- .github/workflows/publish.yml
- build.gradle.kts
- codecov.yml
- settings.gradle.kts
Update to latest plugins and repos
> chore: update to latest
